CREATE TABLE USERS (
    USER_ID INTEGER AUTO_INCREMENT NOT NULL, 
    USERNAME VARCHAR(50) NOT NULL,   
    PASSWORD VARCHAR(150) NOT NULL, 
    ENABLED  TINYINT NOT NULL DEFAULT 1,
    FIRST_NAME varchar(45) DEFAULT NULL,  
    LAST_NAME varchar(45) DEFAULT NULL,  
    EMAIL varchar(45) DEFAULT NULL,  
    PHONE varchar(45) DEFAULT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_ROLES (
    USER_ROLE_ID INTEGER AUTO_INCREMENT NOT NULL,
    USER_ID INTEGER NOT NULL, 
    ROLE VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_ROLE_ID)
);

CREATE TABLE BOOK(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    DATE_RELEASE DATE NOT NULL,
    TYPE_BOOK VARCHAR(100) NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    ISBN VARCHAR(150) NOT NULL,
    AUTHOR VARCHAR(150) NOT NULL,
    PRIMARY KEY (ID)
);

    
    

INSERT INTO USERS (USERNAME,PASSWORD,ENABLED,FIRST_NAME,LAST_NAME,EMAIL,PHONE) VALUES ('admin','123456',1,'Daniel','Cassi','dann.hideki@gmail.com','12-1234-5678');

DROP TABLE USERS
 SHOW TABLES

select * from users;