DROP TABLE USERS;
DROP TABLE USER_ROLES;

CREATE TABLE USERS (
    USER_ID INTEGER AUTO_INCREMENT NOT NULL, 
    USERNAME VARCHAR(50) NOT NULL,   
    PASSWORD VARCHAR(150) NOT NULL, 
    ENABLED  TINYINT NOT NULL DEFAULT 1,
    FIRST_NAME varchar(45) DEFAULT NULL,  
    LAST_NAME varchar(45) DEFAULT NULL,  
    EMAIL varchar(45) DEFAULT NULL,  
    PHONE varchar(45) DEFAULT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE USER_ROLES (
    USER_ROLE_ID INTEGER AUTO_INCREMENT NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    PRIMARY KEY (USER_ROLE_ID)
);

CREATE TABLE BOOK(
    ID INTEGER AUTO_INCREMENT NOT NULL,
    DATE_RELEASE DATE NOT NULL,
    TYPE_BOOK VARCHAR(100) NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    ISBN VARCHAR(150) NOT NULL,
    AUTHOR VARCHAR(150) NOT NULL,
    PRIMARY KEY (ID)
);


ALTER TABLE USERS ADD COLUMN USER_ROLES_ID INT NOT NULL, ADD FOREIGN KEY FK_USER_ROLES_ID (USER_ROLES_ID) REFERENCES USER_ROLES (USER_ROLE_ID); 

INSERT INTO USER_ROLES (ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO USER_ROLES (ROLE) VALUES ('ROLE_USER');
    

INSERT INTO USERS (USERNAME,PASSWORD,ENABLED,FIRST_NAME,LAST_NAME,EMAIL,PHONE,USER_ROLES_ID) VALUES ('admin','123456',1,'Daniel','Cassi','dann.hideki@gmail.com','12-1234-5678',1);

